; homex.g
; called to home the X axis
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)
G91              ; relative positioning
G1 H1 X-700 F6000 ; move X up until the endstop is triggered
G1 X5 F6000 H2
G1 H1 X-700 F180
G90