; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)
G91
G1 H1 Y-2000 F6000 ; move Y up until the endstop is triggered
G1 Y5 F6000 H2       ; move 5mm away with F6000
M584 Y1              ; Seperate Y and U axis
G1 H1 Y-2000 U-2000 F180  ; approach again slowley
M584 Y1:3         ; Join Y and U axis again
G90