; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)
G59.3
G91              ; relative positioning
G1 S1 Y-2000 F6000 ; move Y up until the endstop is triggered
G92 Y0
G1 Y5 F6000
M584 Y1              ; Seperate Y and U axis
G1 S1 Y-2000 U-2000 F180
G92 Y0 U0         ; set Y position to axis minimum (you may want to adjust this)
M584 Y1:3         ; Join Y and U axis again
G54