; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)

M5                   ; Stop Spindle
G53 G1 Z140 F360     ; lift Z to top end

