; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)

M5                   ; Stop Spindle
G53 G0 Z140          ; lift Z to top end

