; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)
G53 G0 Z140           ; got rapid to top height   
M3 S1000              ; start Spindle
G0 R1 X0 Y0           ; go rapid to last xy position at top height
G0 R1 Z10             ; go rapid to 10mm above last position 
G1 R1 X0 Y0 Z0 F100   ; go back to the last print move
