; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)
M3 S1000              ; start Spindle
G1 R1 X0 Y0 Z50 F6000 ; go to 50mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
