; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
M5
; generated by RepRapFirmware Configuration Tool on Wed Sep 12 2018 16:59:43 GMT+0200 (Central European Summer Time)